//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Blog_Uygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public int Blog_ID { get; set; }
        public Nullable<System.DateTime> Yorum_Tarihi { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
